### ISSUE TITLE
Installation Error Occurred: Code: 400. Message: Cannot run program "su": error=2, No such file or directory. Details: Cannot run program "su": error=2, No such file or directory

### ISSUE THREAD

**Issue by wraptor** [ShadyBoshra2012/flutter_install_apk_silently#3]
i try
```
File file = File(fullPath);
int fileSize = 0;
try {
    fileSize = await file.length();
} catch (e) {}
print(fileSize);
```
console print
```
I/flutter (28641): 23547965
```

and i can find apk in my phone file manager.

why  `No such file or directory`

**Comment by ShadyBoshra2012** [comment]
Please, if you are facing this issue till now, provide more codes and the `fullPath` value.

**Comment by justbendev** [comment]
@wraptor Your device is either not rooted , or you are using a hide root feature.
Both are not supported by default, you can still fork the project with your custom path.
