### ISSUE TITLE
Exception: [INSTALL_FAILED_ALREADY_EXISTS]

### ISSUE THREAD

**Issue by areful** [ShadyBoshra2012/flutter_install_apk_silently#4]
if install the same apk twice, then error occured:

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Installation Error Occurred: Code: 1. Message: Failed to install. Details: 	pkg: /XXX/YYY.apk
Failure [INSTALL_FAILED_ALREADY_EXISTS]

any help?

**Comment by ShadyBoshra2012** [comment]
Hello @areful,

That's the right approach handling this. There's no way to install same apk twice!. Why do you need something like that??
